# Generated by Django 4.2.4 on 2023-08-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expenditure', models.DateField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=500)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure.category')),
                ('stage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure.stage')),
            ],
        ),
    ]
